# Generated by Django 4.1.7 on 2023-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
